int APAPI_DEFAULT_SET_NUM = 34;
struct apapi_event_ops APAPI_DEFAULT_EVENT_OPS[] = {
{"rapl:::PACKAGE_ENERGY:PACKAGE0", OP1_DIV_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO, 0xffffffff},
{"rapl:::PACKAGE_ENERGY:PACKAGE1", OP1_DIV_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO, 0xffffffff},
{"rapl:::DRAM_ENERGY:PACKAGE0", OP1_DIV_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO, 0xffffffff},
{"rapl:::DRAM_ENERGY:PACKAGE1", OP1_DIV_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO, 0xffffffff},
{"rapl:::PP0_ENERGY:PACKAGE0", OP1_DIV_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO, 0xffffffff},
{"rapl:::PP0_ENERGY:PACKAGE1", OP1_DIV_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO, 0xffffffff},
{"rapl:::THERMAL_SPEC:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::THERMAL_SPEC:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MINIMUM_POWER:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MINIMUM_POWER:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_POWER:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_POWER:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_TIME_WINDOW:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_TIME_WINDOW:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::PACKAGE_ENERGY_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0xffffffff},
{"rapl:::PACKAGE_ENERGY_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0xffffffff},
{"rapl:::DRAM_ENERGY_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0xffffffff},
{"rapl:::DRAM_ENERGY_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0xffffffff},
{"rapl:::PP0_ENERGY_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0xffffffff},
{"rapl:::PP0_ENERGY_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0xffffffff},
{"rapl:::THERMAL_SPEC_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::THERMAL_SPEC_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MINIMUM_POWER_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MINIMUM_POWER_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_POWER_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_POWER_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_TIME_WINDOW_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"rapl:::MAXIMUM_TIME_WINDOW_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO, 0},
{"nvml:::Tesla_K20c:fan_speed", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0},
{"nvml:::Tesla_K20c:total_memory", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0},
{"nvml:::Tesla_K20c:unallocated_memory", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0},
{"nvml:::Tesla_K20c:allocated_memory", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0},
{"nvml:::Tesla_K20c:power", OP1_SAMPLE1_MUL_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO, 0},
{"nvml:::Tesla_K20c:temperature", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO, 0}
};

struct apapi_event_ops APAPI_DEFAULT_OPS = 
{"default", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO};

/*
int RAPL_DEFAULT_SET_NUM = 28;
struct apapi_event_ops RAPL_DEFAULT_EVENT_OPS[] = {
{"rapl:::PACKAGE_ENERGY:PACKAGE0", OP1_SAMPLE_DIFF, OP2_DIV_DIFF_TIME, STAT_NO, STAT_STATS, STAT_STATS},
{"rapl:::PACKAGE_ENERGY:PACKAGE1", OP1_SAMPLE_DIFF, OP2_DIV_DIFF_TIME, STAT_NO, STAT_STATS, STAT_STATS},
{"rapl:::DRAM_ENERGY:PACKAGE0", OP1_SAMPLE_DIFF, OP2_DIV_DIFF_TIME, STAT_NO, STAT_STATS, STAT_STATS},
{"rapl:::DRAM_ENERGY:PACKAGE1", OP1_SAMPLE_DIFF, OP2_DIV_DIFF_TIME, STAT_NO, STAT_STATS, STAT_STATS},
{"rapl:::PP0_ENERGY:PACKAGE0", OP1_SAMPLE_DIFF, OP2_DIV_DIFF_TIME, STAT_NO, STAT_STATS, STAT_STATS},
{"rapl:::PP0_ENERGY:PACKAGE1", OP1_SAMPLE_DIFF, OP2_DIV_DIFF_TIME, STAT_NO, STAT_STATS, STAT_STATS},
{"rapl:::THERMAL_SPEC:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::THERMAL_SPEC:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MINIMUM_POWER:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MINIMUM_POWER:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_POWER:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_POWER:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_TIME_WINDOW:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_TIME_WINDOW:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::PACKAGE_ENERGY_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::PACKAGE_ENERGY_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::DRAM_ENERGY_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::DRAM_ENERGY_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::PP0_ENERGY_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::PP0_ENERGY_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::THERMAL_SPEC_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::THERMAL_SPEC_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MINIMUM_POWER_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MINIMUM_POWER_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_POWER_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_POWER_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_TIME_WINDOW_CNT:PACKAGE0", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO},
{"rapl:::MAXIMUM_TIME_WINDOW_CNT:PACKAGE1", OP1_NOP, OP2_NOP, STAT_NO, STAT_NO, STAT_NO}
};

int NVML_DEFAULT_SET_NUM = 6;
struct apapi_event_ops NVML_DEFAULT_EVENT_OPS[] = {
{"nvml:::Tesla_K20c:fan_speed", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO},
{"nvml:::Tesla_K20c:total_memory", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO},
{"nvml:::Tesla_K20c:unallocated_memory", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO},
{"nvml:::Tesla_K20c:allocated_memory", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO},
{"nvml:::Tesla_K20c:power", OP1_SAMPLE1_MUL_DIFF_TIME, OP2_NOP, STAT_STATS, STAT_STATS, STAT_NO},
{"nvml:::Tesla_K20c:temperature", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO}
};

int APAPI_cmp_default_names_num = 2;
char *APAPI_cmp_default_names[] = {
"rapl",
"nvml"
};
int APAPI_cmp_default_ops_num[] = {
RAPL_DEFAULT_SET_NUM,
NVML_DEFAULT_SET_NUM
};
struct apapi_event_ops *APAPI_cmp_default_ops[] = {
&RAPL_DEFAULT_EVENT_OPS,
&NVML_DEFAULT_EVENT_OPS
};

struct apapi_event_ops APAPI_DEFAULT_OPS = 
{"default", OP1_NOP, OP2_NOP, STAT_STATS, STAT_NO, STAT_NO};
*/
