# Site settings
title: Ampehre
email: achim.loesch@upb.de
email2: cknorr@mail.upb.de
description: > # this means to ignore newlines until "baseurl:"
    Ampehre is a software framework used to measure the energy consumption
    and power dissipation of computing resources in heterogeneous computing environments.
baseurl: "/"
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: akiml
github_username2: cknorr1

# Build settings
markdown: kramdown
